# Generated by Django 5.2.7 on 2026-04-23 21:01

import sys

from django.core.exceptions import ImproperlyConfigured
from django.db import migrations
from os import getenv
from django.contrib.auth.hashers import make_password

NO_PASSWORD_NOTICE = """
================================================================
No administrator account was created.

ADMIN_PASS is not set, so this migration has nothing safe to use
as a password. To create the initial admin account, set it and
run migrate again:

    ADMIN_PASS='<a strong password>' python manage.py migrate

Optional: ADMIN_USER (default "admin") and ADMIN_EMAIL.
See .env.example.
================================================================
"""


def create_admin_account(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AdminProfile = apps.get_model("tutor", "AdminProfile")

    username = getenv("ADMIN_USER") or "admin"
    email = getenv("ADMIN_EMAIL") or ""
    password = getenv("ADMIN_PASS")

    if not password:
        if User.objects.filter(username=username).exists():
            # Existing deployment: the account is already provisioned, so an
            # upgrade should be a no-op rather than an error.
            return

        if getenv("ADMIN_USER") or getenv("ADMIN_EMAIL"):
            # Half-configured: the operator clearly meant to create an admin.
            raise ImproperlyConfigured(
                "ADMIN_USER/ADMIN_EMAIL are set but ADMIN_PASS is missing. "
                "Set ADMIN_PASS to create the initial admin account."
            )

        # Nothing configured at all (fresh clone, test database, CI). Create no
        # account rather than falling back to a password published in this repo.
        sys.stderr.write(NO_PASSWORD_NOTICE)
        return

    user, created = User.objects.get_or_create(
        username=username,
        defaults={
            "email": email,
            "password": make_password(password),
            "is_staff": True,
            "is_superuser": True,
            "is_active": True,
        },
    )

    if not created and email and user.email != email:
        # Only ever sync the email on an account that already exists. Do not
        # re-grant is_staff/is_superuser/is_active: an operator who demoted or
        # disabled this account should not have it silently re-escalated.
        user.email = email
        user.save(update_fields=["email"])

    AdminProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_admin_account, migrations.RunPython.noop),
    ]
