"""
Django settings for llmsite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Repo root (…/MasteryPilot) — two levels above code/llmsite/.
REPO_ROOT = BASE_DIR.parent.parent

# Load the repo-root .env before anything below reads os.getenv(). The
# languagemodel_* modules also call load_dotenv(), but they run long after
# settings are frozen, so Django's own configuration has to load it here.
# See .env.example for the full list of supported variables.
load_dotenv(REPO_ROOT / ".env")


def _env_flag(name: str, default: bool) -> bool:
    """Read a boolean env var. Accepts 1/true/yes/on, case-insensitively."""
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Email configuration for password reset
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@aitutor.local'

# Enable Gemini (TESTING ONLY)
GEMINI_ENABLED = False

CURRICULUM_ROOT = BASE_DIR / "curriculum"
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB

# LLM to use
LLM_MODULE = "qwen"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to off, so a deployment that forgets to configure anything is safe
# rather than leaking tracebacks. Set DJANGO_DEBUG=1 for local development —
# note that runserver will not serve static files with DEBUG off.
DEBUG = _env_flag("DJANGO_DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DEBUG is off. Generate one with:\n"
            '    python -c "import secrets; print(secrets.token_hex(32))"'
        )
    # Development only. Never reachable with DEBUG off (see above).
    SECRET_KEY = "dev-only-change-me"

# Comma-separated list of hostnames this site answers to, e.g.
# DJANGO_ALLOWED_HOSTS=tutor.example.edu,192.168.1.50
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'tutor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'llmsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'llmsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site configuration
SITE_ID = 1

# Cookie and transport hardening.
#
# The Secure flag tells the browser to send a cookie over HTTPS only, so
# turning it on without TLS silently breaks login (the CSRF token never
# reaches the server). Both cookies are therefore gated on one switch, which
# defaults to on in production and off in development. Set
# DJANGO_SECURE_COOKIES=0 if you deploy on plain HTTP over a trusted LAN —
# and understand that session cookies then travel in cleartext.
SECURE_COOKIES = _env_flag("DJANGO_SECURE_COOKIES", not DEBUG)

CSRF_COOKIE_SECURE = SECURE_COOKIES
SESSION_COOKIE_SECURE = SECURE_COOKIES

# Redirecting HTTP to HTTPS is opt-in and off by default, unlike the cookie
# flags above. It is not safe to infer from DEBUG: this project's own
# setup.sh serves plain HTTP with no proxy, and behind a TLS-terminating
# proxy an unconditional redirect loops forever unless Django is also told
# how to recognise an already-secure request. Turn both on together.
SECURE_SSL_REDIRECT = _env_flag("DJANGO_SECURE_SSL_REDIRECT", False)
if _env_flag("DJANGO_TRUST_PROXY_SSL_HEADER", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Note: CSRF_COOKIE_HTTPONLY must remain False because the frontend
# reads the CSRF token from the cookie via JavaScript (getCookie("csrftoken")).
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Origins allowed to submit cross-origin POSTs, e.g.
# DJANGO_CSRF_TRUSTED_ORIGINS=https://tutor.example.edu
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

